//
// Generated file, do not edit! Created by opp_msgtool 6.4 from ospf.msg.
//

#ifndef __OSPF_M_H
#define __OSPF_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Mess;
/**
 * Class generated from <tt>ospf.msg:6</tt> by opp_msgtool.
 * <pre>
 * message Mess
 * {
 *     uint8_t payload[]; // Dữ liệu gói tin OSPF
 * }
 * </pre>
 */
class Mess : public ::omnetpp::cMessage
{
  protected:
    uint8_t *payload = nullptr;
    size_t payload_arraysize = 0;

  private:
    void copy(const Mess& other);

  protected:
    bool operator==(const Mess&) = delete;

  public:
    Mess(const char *name=nullptr, short kind=0);
    Mess(const Mess& other);
    virtual ~Mess();
    Mess& operator=(const Mess& other);
    virtual Mess *dup() const override {return new Mess(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setPayloadArraySize(size_t size);
    virtual size_t getPayloadArraySize() const;
    virtual uint8_t getPayload(size_t k) const;
    virtual void setPayload(size_t k, uint8_t payload);
    virtual void insertPayload(size_t k, uint8_t payload);
    [[deprecated]] void insertPayload(uint8_t payload) {appendPayload(payload);}
    virtual void appendPayload(uint8_t payload);
    virtual void erasePayload(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Mess& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Mess& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Mess *fromAnyPtr(any_ptr ptr) { return check_and_cast<Mess*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OSPF_M_H

