//
// Generated file, do not edit! Created by opp_msgtool 6.4 from ospf.msg.
//

#ifndef __OSPF_M_H
#define __OSPF_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class OspfMess;
/**
 * Class generated from <tt>ospf.msg:6</tt> by opp_msgtool.
 * <pre>
 * message OspfMess
 * {
 *     uint8_t version;
 *     uint8_t type;
 *     uint16_t length;
 *     uint32_t routerId;
 *     uint32_t areaId;
 *     uint16_t checksum;
 *     uint16_t authType;
 *     uint32_t authData1;
 *     uint32_t authData2;
 *     uint8_t payload[]; // Dữ liệu gói tin OSPF
 * }
 * </pre>
 */
class OspfMess : public ::omnetpp::cMessage
{
  protected:
    uint8_t version = 0;
    uint8_t type = 0;
    uint16_t length = 0;
    uint32_t routerId = 0;
    uint32_t areaId = 0;
    uint16_t checksum = 0;
    uint16_t authType = 0;
    uint32_t authData1 = 0;
    uint32_t authData2 = 0;
    uint8_t *payload = nullptr;
    size_t payload_arraysize = 0;

  private:
    void copy(const OspfMess& other);

  protected:
    bool operator==(const OspfMess&) = delete;

  public:
    OspfMess(const char *name=nullptr, short kind=0);
    OspfMess(const OspfMess& other);
    virtual ~OspfMess();
    OspfMess& operator=(const OspfMess& other);
    virtual OspfMess *dup() const override {return new OspfMess(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint8_t getVersion() const;
    virtual void setVersion(uint8_t version);

    virtual uint8_t getType() const;
    virtual void setType(uint8_t type);

    virtual uint16_t getLength() const;
    virtual void setLength(uint16_t length);

    virtual uint32_t getRouterId() const;
    virtual void setRouterId(uint32_t routerId);

    virtual uint32_t getAreaId() const;
    virtual void setAreaId(uint32_t areaId);

    virtual uint16_t getChecksum() const;
    virtual void setChecksum(uint16_t checksum);

    virtual uint16_t getAuthType() const;
    virtual void setAuthType(uint16_t authType);

    virtual uint32_t getAuthData1() const;
    virtual void setAuthData1(uint32_t authData1);

    virtual uint32_t getAuthData2() const;
    virtual void setAuthData2(uint32_t authData2);

    virtual void setPayloadArraySize(size_t size);
    virtual size_t getPayloadArraySize() const;
    virtual uint8_t getPayload(size_t k) const;
    virtual void setPayload(size_t k, uint8_t payload);
    virtual void insertPayload(size_t k, uint8_t payload);
    [[deprecated]] void insertPayload(uint8_t payload) {appendPayload(payload);}
    virtual void appendPayload(uint8_t payload);
    virtual void erasePayload(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OspfMess& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OspfMess& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline OspfMess *fromAnyPtr(any_ptr ptr) { return check_and_cast<OspfMess*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OSPF_M_H

